## Feed-Forward Neural Network

In [44]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import itertools

In [43]:
!pip install scikeras keras

In [36]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from keras.optimizers import Adam
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from scikeras.wrappers import KerasClassifier, KerasRegressor
from sklearn.metrics import classification_report, confusion_matrix, multilabel_confusion_matrix
from sklearn.metrics import mean_squared_error, accuracy_score, precision_score, recall_score

In [29]:
df = pd.read_csv('features.csv')

x = df.drop(columns = ['Breed'])
y = df['Breed']
num_classes = 120
display(df.head())
print(f"Number of Breeds: {num_classes}")

Breed  Feature 0  Feature 1  Feature 2  Feature 3  Feature 4  \
0  brittany_spaniel  -5.279870  -2.208426   5.211814  -8.099501 -13.185220   
1  brittany_spaniel   0.524020  -4.321692  -5.808849  -0.097443 -13.157566   
2  brittany_spaniel   4.484349 -11.409184  -2.061785  -8.795961 -10.736951   
3  brittany_spaniel   8.630311  -9.028896  -4.177602  -3.575223  -7.698362   
4  brittany_spaniel  -6.459163  -5.178344   3.182314  -6.884826  -2.663270   

   Feature 5  Feature 6  Feature 7  Feature 8  ...  Feature 90  Feature 91  \
0  -0.753768  -3.015471   0.825370  -4.269372  ...   -0.465695   -0.674558   
1   0.439865  -4.521323  -1.382092  -1.304059  ...   -0.410429    0.396908   
2  -0.650287   0.697348   8.464226  -2.961214  ...   -1.486026    0.636264   
3  -5.857273  -3.473359   6.915802   1.972978  ...   -1.718268    0.056995   
4  -0.779802  -0.788943   4.521932  -3.636744  ...   -0.964177    0.368517   

   Feature 92  Feature 93  Feature 94  Feature 95  Feature 96  Feature 97  \
0    0.123558   -1.240681   -1.069499   -0.714136    1.011624   -0.225715   
1    0.344853    0.243527   -0.416206    0.310021    0.025371   -0.221647   
2   -0.315544    1.400241   -0.116869   -0.253275    0.918089   -0.645903   
3    0.152345    0.562226    0.279578   -0.277104   -0.956852   -0.531012   
4   -0.274313   -0.534803    0.797063   -0.156896    1.027882    1.130965   

   Feature 98  Feature 99  
0   -0.220330    1.140998  
1   -0.306602   -0.855617  
2    0.545067   -1.274210  
3    0.249064   -1.877944  
4    0.696718    0.098893  

[5 rows x 101 columns]

Number of Breeds: 120


In [30]:
# Define hyperparameters

# TEST_SIZE = 0.4
# LEARN_RATE = 0.001
# FIRST_LAYER = 128 
# ACTIVATION_1 = 'relu'
# SECOND_LAYER = 64
# ACTIVATION_2 = 'relu'
# ACTIVATION_OUT = 'softmax'
# LOSS_TYPE = 'categorical_crossentropy'
# METRICS = ['accuracy']
# EPOCHS = 20


In [48]:
param_grid = {
    'first_layer': [2, 4, 8, 32, 64, 128],
    'second_layer': [4, 16, 32, 64],
    'activation_1': ['relu', 'tanh'],
    'activation_2': ['relu', 'tanh'],
    'activation_out': ['softmax'],
    'learn_rate': [0.0001, 0.0005, 0.001, 0.005, .01],
    'batch_size' : [10, 20, 50, 100]
    'epochs' : [10, 20]
}
ACTIVATION_1 = 'relu'
ACTIVATION_2 = 'relu'
ACTIVATION_OUT = 'softmax'
TEST_SIZE = 0.4
EPOCHS = 20
METRICS = ['accuracy']
LOSS_TYPE = 'categorical_crossentropy'

In [32]:
x = df.drop(columns=['Breed'])
y = df['Breed']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = TEST_SIZE)

# Encode the categorical target variable
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Convert the encoded labels to one-hot encoding
y_train = to_categorical(y_train_encoded, num_classes=num_classes)
y_test = to_categorical(y_test_encoded, num_classes=num_classes)

In [33]:
def create_model(first_layer=128, activation_1='relu', second_layer=64, activation_2='relu', activation_out='softmax', learn_rate=0.001):
    model = Sequential()
    model.add(Dense(first_layer, input_shape=(100,), activation=activation_1))
    model.add(Dense(second_layer, activation=activation_2))
    model.add(Dense(num_classes, activation=activation_out))
    model.compile(optimizer=Adam(learning_rate=learn_rate), loss=LOSS_TYPE, metrics=METRICS)
    return model

model = create_model()

# Train the model
model.fit(x_train, y_train, epochs=EPOCHS, batch_size=32, validation_data=(x_test, y_test))

# Make predictions
y_pred = model.predict(x_test)

Epoch 1/20
383/383 [==============================] - 1s 2ms/step - loss: 2.0991 - accuracy: 0.5137 - val_loss: 0.9326 - val_accuracy: 0.7228
Epoch 2/20
383/383 [==============================] - 1s 1ms/step - loss: 0.7194 - accuracy: 0.7833 - val_loss: 0.7441 - val_accuracy: 0.7644
Epoch 3/20
383/383 [==============================] - 1s 1ms/step - loss: 0.5618 - accuracy: 0.8211 - val_loss: 0.7361 - val_accuracy: 0.7720
Epoch 4/20
383/383 [==============================] - 1s 1ms/step - loss: 0.4772 - accuracy: 0.8469 - val_loss: 0.7419 - val_accuracy: 0.7783
Epoch 5/20
383/383 [==============================] - 1s 1ms/step - loss: 0.4181 - accuracy: 0.8645 - val_loss: 0.7413 - val_accuracy: 0.7807
Epoch 6/20
383/383 [==============================] - 1s 1ms/step - loss: 0.3675 - accuracy: 0.8799 - val_loss: 0.7536 - val_accuracy: 0.7785
Epoch 7/20
383/383 [==============================] - 1s 1ms/step - loss: 0.3288 - accuracy: 0.8925 - val_loss: 0.7883 - val_accuracy: 0.7796
Epoch 

In [37]:
# Convert continuous predictions to class labels
y_pred_classes = np.argmax(y_pred, axis=1)

# Convert one-hot encoded y_test back to class labels
y_test_classes = np.argmax(y_test, axis=1)

# Inverse transform the predicted and ground truth class labels to original breed names
y_pred_breed = label_encoder.inverse_transform(y_pred_classes)
y_test_breed = label_encoder.inverse_transform(y_test_classes)

# Evaluate the model
loss, accuracy = model.evaluate(x_test, y_test)
print(f'Test Accuracy: {accuracy}')

#print("Accuracy : ", accuracy_score(y_test, y_pred))
#print("Mean Square Error : ", mean_squared_error(y_test, y_pred))

print("Confusion Matrix for each label : ")
print(multilabel_confusion_matrix(y_test_breed, y_pred_breed))

print("Classification Report : ")
print(classification_report(y_test_breed, y_pred_breed))

256/256 [==============================] - 0s 726us/step - loss: 1.2570 - accuracy: 0.7646
Test Accuracy: 0.7645618915557861
Confusion Matrix for each label : 
[[[8110    5]
  [   4   53]]

 [[8061   12]
  [  16   83]]

 [[8105    6]
  [   5   56]]

 [[8074   23]
  [  16   59]]

 [[8089   16]
  [  34   33]]

 [[8067   40]
  [  20   45]]

 [[8079    8]
  [  36   49]]

 [[8072   13]
  [  20   67]]

 [[8084    8]
  [  20   60]]

 [[8076   19]
  [  20   57]]

 [[8091   10]
  [   3   68]]

 [[8075   14]
  [   9   74]]

 [[8094   15]
  [   8   55]]

 [[8092   12]
  [  13   55]]

 [[8081   16]
  [  10   65]]

 [[8091   16]
  [  38   27]]

 [[8102    5]
  [  11   54]]

 [[8098    6]
  [  13   55]]

 [[8096    8]
  [  14   54]]

 [[8099   15]
  [  12   46]]

 [[8094   12]
  [  15   51]]

 [[8113    7]
  [   6   46]]

 [[8093   19]
  [  17   43]]

 [[8097    9]
  [  17   49]]

 [[8104    7]
  [  11   50]]

 [[8082   17]
  [  18   55]]

 [[8097    9]
  [  21   45]]

 [[8102    7]
  [  17   46]]



In [49]:
def perform_grid_search(x_train, y_train, x_test, y_test, param_grid):
    best_accuracy = 0
    best_params = {}

    # Iterate over all combinations of hyperparameters
    for batch_size, epoch, first_layer, second_layer, learn_rate in itertools.product(param_grid['batch_size'], param_grid['epochs'], param_grid['first_layer'], param_grid['second_layer'], param_grid['learn_rate']):
        # Build the model
        model = Sequential()
        model.add(Dense(first_layer, input_shape=(100,), activation=ACTIVATION_1))  # Assuming 100 features
        model.add(Dense(second_layer, activation=ACTIVATION_2))
        model.add(Dense(num_classes, activation=ACTIVATION_OUT))  # num_classes is the number of unique breed labels
        model.compile(optimizer=Adam(learning_rate=learn_rate), loss=LOSS_TYPE, metrics=METRICS)
        
        # Train the model
        model.fit(x_train, y_train, epochs=epoch, batch_size=batch_size, verbose=0)
        
        # Evaluate the model
        y_pred = model.predict(x_test)
        accuracy = accuracy_score(np.argmax(y_test, axis=1), np.argmax(y_pred, axis=1))
        
        # Check if current combination is better than the previous best
        if accuracy > best_accuracy:
            best_accuracy = accuracy
            best_params = {
                'batch_size': batch_size,
                'epochs': epoch,
                'first_layer': first_layer,
                'second_layer': second_layer,
                'learn_rate': learn_rate
            }

    return best_accuracy, best_params

# Usage example:
best_accuracy, best_params = perform_grid_search(x_train, y_train, x_test, y_test, param_grid)
print("Best accuracy: %f" % best_accuracy)
print("Best parameters:", best_params)

256/256 [==============================] - 0s 596us/step


KeyboardInterrupt: 